# Generated by Django 6.0.3 on 2026-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default=12),
            preserve_default=False,
        ),
    ]
